### ISSUE TITLE
Having an issue when trying to delete the thread.class from the database through my DBHelper class

### ISSUE THREAD

**Issue by CMarshall92** [CMarshall92/Not-Another-Reddit#13]
Seems to delete everything else but wont delete the threads data from the database.

org.hibernate.HibernateException: More than one row with the given identifier was found: 1, for class: models.ThreadDescription
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:100)
	at org.hibernate.loader.entity.EntityLoader.loadByUniqueKey(EntityLoader.java:161)
	at org.hibernate.persister.entity.AbstractEntityPersister.loadByUniqueKey(AbstractEntityPersister.java:2385)
	at org.hibernate.type.EntityType.loadByUniqueKey(EntityType.java:767)
	at org.hibernate.type.EntityType.resolve(EntityType.java:505)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:170)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:144)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1114)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:972)
	at org.hibernate.loader.Loader.doQuery(Loader.java:920)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2553)
	at org.hibernate.loader.Loader.doList(Loader.java:2539)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2369)
	at org.hibernate.loader.Loader.list(Loader.java:2364)
	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1682)
	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
	at db.DBHelper.deleteAll(DBHelper.java:38)
	at db.Seed.main(Seed.java:24)

**Comment by CMarshall92** [comment]
Fixed the issue if you come across this check that you dont have.

fetch = FetchType.LAZY

Attached to both of the one to ones.
